// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLzmT_5w0dsSD75I8yX5RUQl7RXJPkf5g',
    appId: '1:203149063807:web:e2f0f7797acbd643c7714a',
    messagingSenderId: '203149063807',
    projectId: 'emailsigninaddproductfirebase',
    authDomain: 'emailsigninaddproductfirebase.firebaseapp.com',
    storageBucket: 'emailsigninaddproductfirebase.appspot.com',
    measurementId: 'G-DK25X4MES5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm7CxfRkNzaC2gNaeUVzZUhU_9YfX07gY',
    appId: '1:203149063807:android:bc15c172b8faea1ec7714a',
    messagingSenderId: '203149063807',
    projectId: 'emailsigninaddproductfirebase',
    storageBucket: 'emailsigninaddproductfirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATVzwE6n9fYVfzJZi5aZx3CGcHrgQ_-Ww',
    appId: '1:203149063807:ios:581702f686ad84abc7714a',
    messagingSenderId: '203149063807',
    projectId: 'emailsigninaddproductfirebase',
    storageBucket: 'emailsigninaddproductfirebase.appspot.com',
    iosClientId: '203149063807-126pbu6to6bdsjt8hag6djk1tbanm8lf.apps.googleusercontent.com',
    iosBundleId: 'com.example.addprouctfirebase',
  );
}
